# Generated by Django 3.2 on 2023-02-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_news', models.CharField(max_length=120, verbose_name='Номер статьи')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Нововведения',
                'verbose_name_plural': 'Нововведения',
            },
        ),
    ]
